In [109]:
import random

# Для создания кодов используем большой диапазон, чтобы
# свести к минимуму вероятность повторяющихся кодов
for i in range(21):
    code = random.randint(1000, 10000)
    print(f'code {i}: {code}')

code 0: 3120
code 1: 7509
code 2: 1066
code 3: 4283
code 4: 3428
code 5: 5078
code 6: 3420
code 7: 3333
code 8: 3695
code 9: 2570
code 10: 6628
code 11: 4396
code 12: 4097
code 13: 5080
code 14: 6558
code 15: 2588
code 16: 2729
code 17: 5616
code 18: 5161
code 19: 5073
code 20: 1804


In [110]:
import random

# Создание списка для возможности работы с кодами
list = []

# Для создания кодов используем большой диапазон, чтобы
# свести к минимуму вероятность повторяющихся кодов
for i in range(21):
    code = random.randint(1000, 10000)
    add_code = list.append(code)
    print(f'code {i}: {code}')
    
# Упаковка полученного списка в неизменяемый (кортеж)
all_codes = tuple(list)

# Вывод на экран каждого пятого кода (призового) через срез
print(f'Призовые коды: {all_codes[::5]}')

code 0: 9943
code 1: 2167
code 2: 3539
code 3: 9309
code 4: 4079
code 5: 9680
code 6: 1961
code 7: 8790
code 8: 3666
code 9: 4624
code 10: 4643
code 11: 5764
code 12: 3727
code 13: 6486
code 14: 1257
code 15: 1808
code 16: 6487
code 17: 7120
code 18: 2121
code 19: 2477
code 20: 5748
Призовые коды: (9943, 9680, 4643, 1808, 5748)


In [111]:
import random

list_code = []

i = 1
while i < 21:
    code = random.randint(1, 20)
    for _ in range(21):
        if code in list_code:
            code = 0
        if code != 0:
            list_code.append(code)
            print(f'code {i}: {code}')
            i += 1
all_codes = tuple(list_code)
print('Призовые коды: ', all_codes[::5])

code 1: 20
code 2: 1
code 3: 4
code 4: 5
code 5: 13
code 6: 17
code 7: 19
code 8: 14
code 9: 10
code 10: 11
code 11: 15
code 12: 9
code 13: 2
code 14: 7
code 15: 6
code 16: 16
code 17: 18
code 18: 8
code 19: 3
code 20: 12
Призовые коды:  (20, 17, 15, 16)


In [112]:
A = dict(d1='one', d2=2, d3=['t','h','r','e','e'])
print(A)

B = dict([(1,'one'), (2,2), (3,['t','h','r','e','e'])])
print(B)

C = dict.fromkeys(['d1','d2','d3'])
print(C)

D = dict.fromkeys(['b1','b2','b3'], 50)
print(D)

{'d1': 'one', 'd2': 2, 'd3': ['t', 'h', 'r', 'e', 'e']}
{1: 'one', 2: 2, 3: ['t', 'h', 'r', 'e', 'e']}
{'d1': None, 'd2': None, 'd3': None}
{'b1': 50, 'b2': 50, 'b3': 50}


In [113]:
E = {'d1':'one', 'd2':2, 'd3':['t','h','r','e','e']}
E['d4'] = [*range(4)]
print(E)

# Создание еще одного ключа 'd3_new' для переноса
# значения из ключа 'd3'
E['d3_new'] = E['d3']
# Обновление значения для ключа 'd3'
E['d3'] = 'three'
print(E)

{'d1': 'one', 'd2': 2, 'd3': ['t', 'h', 'r', 'e', 'e'], 'd4': [0, 1, 2, 3]}
{'d1': 'one', 'd2': 2, 'd3': 'three', 'd4': [0, 1, 2, 3], 'd3_new': ['t', 'h', 'r', 'e', 'e']}


In [114]:
A = {'d1': 'one', 'd2': 2, 'd3': ['t','h','r','e','e']}
print(A.get('d4'))
print(A.get('d4', 'Stop out!'))

None
Stop out!


In [115]:
A = {'234':'Блокнот А4', '915':'БлокнотА3', '37':'Блокнот А2', '7373':'Блокнот А1'}

# Создание списка из ключей
list_keys = [*A.keys()]
print(list_keys)

# Сортировка списка ключей в алфавитном порядке
list_keys.sort()
print(list_keys)

# Теперь у каждого ключа есть свой индекс
for i in list_keys:
    print(f'{i}:{A[i]}')

['234', '915', '37', '7373']
['234', '37', '7373', '915']
234:Блокнот А4
37:Блокнот А2
7373:Блокнот А1
915:БлокнотА3


In [116]:
def fibonacci_sequence(L):
    '''Последовательность Фибоначчи'''
    if len(L) < 2:
        return L
    fib_sequence = L[:2]
    for i in range(2, len(L)):
        next_num = fib_sequence[i-1] + fib_sequence[i-2]
        fib_sequence.append(next_num)
    return fib_sequence

L = [0, 1, 1, 1, 1, 1]

fib_sequence = fibonacci_sequence(L)
print(fib_sequence)  

[0, 1, 1, 2, 3, 5]


In [ ]:
def transform_number(num: int) -> int:
    '''
    Преобразовывет последовательность чисел в сумму
    первой и последней цифры. 
    Пример: 143562 -> 3108 (1+2, 4+6, 3+5)
    '''
    digits = list(str(num))               # превращаем число в список строковых цифр
    result = []

    half = len(digits) // 2
    for i in range(half):     # перебираем половину списка
        left = int(digits[i])             # цифра с начала
        right = int(digits[-(i + 1)])     # цифра с конца
        result.append(str(left + right))  # суммируем и записываем как строку
        
    # если нечётное количество цифр — добавляем среднюю
    if len(digits) % 2 == 1:
        middle = digits[half]
        result.append(middle)

    return int(''.join(result))           # собираем строку обратно в число

print(transform_number(143562))  # → 3108
print(transform_number(123456))  # → 777
print(transform_number(987654))  # → 131313
print(transform_number(1234))
print(transform_number(12345))   # → 663  (1+5, 2+4, середина 3)
print(transform_number(123))

In [7]:
diet = {"а": 1, "Ь": 2}

for key in diet.keys():
    print (key, " => ", diet[key])
print() 

for key in sorted(diet.keys()):
    print(key, " => ", diet[key])

а  =>  1
Ь  =>  2

Ь  =>  2
а  =>  1


In [15]:
from fractions import Fraction

a = Fraction (6, 4)
b = Fraction (7, 12)
print (a + b)
print (a * b)

# Получение числителя/знаменателя
c = a * b
print(c.numerator)
print(c.denominator)

# Ограничение значения знаменателя
print(c.limit_denominator(8))

# Преобразование из float в дробь
x = 5.75
y = Fraction(*x.as_integer_ratio())
print(y) 

25/12
7/8
7
8
7/8
23/4


In [17]:
template = f"""
<html>
    <head>
    <title>%(title)s</title>
    </head>
    <body>
        %(text)s
    </body>
</html>
"""

data = {"title": "Мой сайт", "text": "Контент"}

print(template % data)


<html>
    <head>
    <title>Мой сайт</title>
    </head>
    <body>
        Контент
    </body>
</html>



In [19]:
import hashlib

hash = hashlib.md5(b"secret")
print(hash.digest())
print(hash.hexdigest())

b'^\xbe"\x94\xec\xd0\xe0\xf0\x8e\xabv\x90\xd2\xa6\xeei'
5ebe2294ecd0e0f08eab7690d2a6ee69


In [31]:
'''Работа со списками'''

# Создание вложенных списков
lst = [[i] for i in range(3)]
print(lst)

# Элементы списка в обратном порядке
lst = [1, 2, 3, 4, 5, 6, 7]
print(lst[::-1])

# Изменение элементов списка с помощью среза
lst = [1, 2, 3, 4, 5, 6, 7]
lst[1:3] = [8, 9]
print(lst)

# Конкатенация списков
lst = [1, 2, 3, 4, 5, 6, 7]
lst2 = [10, 11, 12]
lst3 = lst + lst2
print(lst3)

# Если нужно добавить элементы в текущий список,
# можно использовать оператор +=
lst = [1, 2, 3, 4, 5, 6, 7]
lst += [10, 11, 12]
print(lst)

[[0], [1], [2]]
[7, 6, 5, 4, 3, 2, 1]
[1, 8, 9, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 10, 11, 12]
[1, 2, 3, 4, 5, 6, 7, 10, 11, 12]


In [41]:
'''Вычисления с большими числовыми массивами'''

# Списки Python
a = [2, 2, 2, 2]
b = [3, 3, 3, 3]
print(a * 2)
print(a + b)

# Массивы Numpy
import numpy as np
an = np.array([2, 2, 3, 3])
bn = np.array([5, 5, 7, 7])
print(an * 2)
print(an + 10)
print(an + bn)
print(an * bn)

[2, 2, 2, 2, 2, 2, 2, 2]
[2, 2, 2, 2, 3, 3, 3, 3]
[4 4 6 6]
[12 12 13 13]
[ 7  7 10 10]
[10 10 21 21]


In [44]:
import numpy as np
# Двумерная таблица 10 000 х 10 000
grid = np.zeros(shape=(10000,10000), dtype=float)
print(grid)
print()
# Все обычные операции все еще применяются
# ко всем элементам одновременно
grid += 100
print(grid)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

[[100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 ...
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]]


In [53]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print()

# Ряд 0
print(a[0])

# Колонка 1
print(a[:, 1])

print()
# Выбираем фрагмент массива и изменяем его
print(a[1:3, 1:3])
print()
a[1:3, 1:3] += 10
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]
[ 2  6 10]

[[ 6  7]
 [10 11]]

[[ 1  2  3  4]
 [ 5 16 17  8]
 [ 9 20 21 12]]
